add gpio to cdserver, first step adjust folder structure

diff --git a/services/init.d/gpioserver b/services/init.d/gpioserver
--- a/services/init.d/gpioserver
+++ b/services/init.d/gpioserver
@@ -10,50 +10,76 @@
 # Description:       starts the gpio server
 ### END INIT INFO
 
-CDSERVER_HOME=//home/cds
 
-DESC="gpio_server"
+DESC="gpioserver for CT io controll"
+NAME=gpio_server
+
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
-SERVER ="//home/cds/.rvm/bin/bootup_gpioserver" 
 
+DAEMON=//home/cds/.rvm/bin/bootup_gpioserver
+DAEMON=/home/rvm/.rvm/wrappers/cinch/smfbot
 
-DAEMON=//home/cds/.rvm/bin/bootup_god
 DAEMON_HOME=//home/cds/CDServer
-DAEMON_LOG=$DAEMON_HOME/log/god.log
-DAEMON_CONFIG=$DAEMON_HOME/cds.god.rb
-DAEMON_OPTS="-c $DAEMON_CONFIG -l $DAEMON_LOG"
-NAME=god
-DESC=god
-USER=cds
+DAEMON_LOG=$DAEMON_HOME/log/gpio_server.log
+DAEMON_OPTS="-e production -p 8970"
+PID=/run/cpioserver.pid
+VERBOSE=y
 
-test -x $DAEMON || exit 0
-
+#
+# Function that starts the daemon/service
+#
+# Return
+# 0 if daemon has been started
+# 1 if daemon was already running
+# 2 if daemon could not be started
+do_start()
+{
+    start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null || return 1
+    start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- $DAEMON_OPTS 2>/dev/null || return 2
+}
+#
+# Function that stops the daemon/service
+#
+# Return
+# 0 if daemon has been stopped
+# 1 if daemon was already stopped
+# 2 if daemon could not be stopped
+# other if a failure occurred
+do_stop()
+{
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --name $NAME
+    RETVAL="$?"
+    sleep 1
+    return "$RETVAL"
+}
 case "$1" in
-  start)
-        echo -n "Starting $DESC: "
-        start-stop-daemon -v --chuid cds:cds --start --exec $DAEMON -- start cds $DAEMON_OPTS
-        echo -n "$NAME."
-        ;;
-  stop)
-        echo -n "Stopping $DESC: "
-        start-stop-daemon -v --start --exec $DAEMON -- terminate cds
-        echo "$NAME."
-        ;;
-  restart|force-reload)
-        echo -n "Restarting $DESC: "
-        start-stop-daemon -v --start --exec $DAEMON -- restart cds
-        echo "$NAME."
-        ;;
-  reload)
-          echo -n "Reloading $DESC configuration: "
-        start-stop-daemon -v --start --exec $DAEMON -- load cds $DAEMON_OPTS
-          echo "$NAME."
-          ;;
-      *)
-            N=/etc/init.d/$NAME
-            echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-            exit 1
-            ;;
-    esac
-
-    exit 0
+start)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+esac
+;;
+stop)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+esac
+;;
+restart)
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    $0 stop &&
+    $0 start ||
+exit $?
+;;
+status)
+    status_of_proc -p $PID "$DAEMON" "$NAME" || exit $?
+    ;;
+    *)
+    echo "Usage: $NAME {start|stop|restart|status}" >&2
+    exit 3
+;;
+esac
